# Generated by Django 3.0 on 2019-12-12 16:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_field',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
